# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
      pin:
        description: '6 digits PIN'
        required: true
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Create User
      run: sudo useradd -m user && sudo adduser root sudo && echo 'user:root' | sudo chpasswd
    - name: Doanload & Install files
      run: | 
        echo Update: APT
        sudo apt update
        echo Install: Ubuntu Desktop
        sudo apt install ubuntu-desktop
        echo Download: Chrome
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        echo Install: Chrome
        sudo dpkg --install google-chrome-stable_current_amd64.deb
        sudo apt install --assume-yes --fix-broken
        echo Install: Xbase Clients
        sudo apt-get install xbase-clients python3-psutil xvfb -y
        echo Install: Chrome Remote Desktop
        wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
        sudo dpkg --install chrome-remote-desktop_current_amd64.deb
        sudo apt install --assume-yes --fix-broken
        echo Download: Keep Alive
        wget https://raw.githubusercontent.com/fakhrureza1/wkwk/main/loop.sh
    - nama    : Mulai Chrome Desktop Jarak Jauh
      jalankan  : $ {{ github.event.inputs.code }} -pin=$ {{ github.event.inputs.pin }}
    - nama : Selesai! Anda dapat melihat mesin dalam daftar sekarang.
      jalankan /   : bash loop.sh
kami
